### ISSUE TITLE
请问能给发一下处理好的BIO数据集吗？  谢谢了

### ISSUE THREAD

**Issue by heroazhe** [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch#1]

**Comment by PeijiYang** [comment]
给我邮箱，私发给你

**Comment by heroazhe** [comment]
> 给我邮箱，私发给你

690468229@qq.com   十分感谢！

**Comment by BlueSkyBubble** [comment]
能不能给我也发一份处理好的数据集？邮箱：896446145@qq.com
十分感谢！！！

**Comment by hertz-pj** [comment]
已经把转换的脚本clue_process.py上传了。

**Comment by topDreamer** [comment]
同求一份处理好的数据集？邮箱：13462749888@163.com
十分感谢！！！

**Comment by hertz-pj** [comment]
> 同求一份处理好的数据集？邮箱：[13462749888@163.com](mailto:13462749888@163.com)
> 十分感谢！！！

请直接使用clue_process.py转换。

**Comment by Hutonway** [comment]
> 给我邮箱，私发给你

你好，可以也给我发一份处理好的数据集吗，谢谢了！413537131@qq.com
