### ISSUE TITLE
您好，使用我的数据存在一个bug

### ISSUE THREAD

**Issue by xhw205** [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch#10]
我遇到一个bug， 模型在训练阶段验证准确率是80%，然后我save模型后测试同一批数据，准确率很低很低
，然后我把save的模型 backward 训练一轮 再测试数据了下，准确率又上去了  很奇怪

**Comment by hertz-pj** [comment]
感觉是模型save的问题，最近暂时没有时间处理这份代码，如果你找到解决方法了可以告诉我。

**Comment by xhw205** [comment]
我把 get_label() 这个函数直接写死了，例如
`
    def get_labels(self):
        return ['B-CHECK', 'E-SIGNS', 'B-DISEASE', 'I-DISEASE', 'E-DISEASE', 'I-SIGNS', 'E-TREATMENT', 'O', 'E-BODY',
                'I-BODY', 'S-SIGNS', 'S-CHECK', 'B-SIGNS', 'B-TREATMENT', 'I-TREATMENT', 'E-CHECK', 'S-BODY', 'B-BODY',
                'I-CHECK']
`
然后就没出现这个bug，有可能是你之前使用的是 set( ) 类型，每一次运行可能是导致数据对应的 label 值随机的

**Comment by hertz-pj** [comment]
呃呃，看来是这个问题，预测和训练时label id变了，感谢。
