### ISSUE TITLE
已经下载了预训练模型在本地，为何还需要从s3下载模型？

### ISSUE THREAD

**Issue by ParkHM17** [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch#11]

**Comment by hertz-pj** [comment]
路径改成本地模型所在地址，应该就不需要下载了

**Comment by ParkHM17** [comment]
> 路径改成本地模型所在地址，应该就不需要下载了

那可以请您提供一下ner.py和model.py的代码么？（新手上手，改了一上午的路径，没解决这个问题~。不胜感激！

**Comment by hertz-pj** [comment]
readme中的使用方法，把第一句
`BERT_BASE_DIR=bert-base-chinese`中的bert-base-chinese改成你下载模型的文件夹路径。

**Comment by ParkHM17** [comment]
> readme中的使用方法，把第一句
> `BERT_BASE_DIR=bert-base-chinese`中的bert-base-chinese改成你下载模型的文件夹路径。

我是这样做的：
1.首先我已经下载了预训练模型，放在了根目录下，目录树是这样的：
|-BERT-BiLSTM-CRF-NER-pytorch
  |-……
  |-bert-base-chinese
    |-config.json
    |-pytorch.model.bin
    |-vocab.txt
2.我将ner.py中的 model_name_or_path参数 改成了这样：
`parser.add_argument("--model_name_or_path", default="bert-base-chinese", type=str)`
（这样的效果应该和您说的改`BERT_BASE_DIR=bert-base-chinese`是一样的吧？）

**Comment by hertz-pj** [comment]
你把文件夹命名也改了，不要用bert-base-chinese，改成bert_base之类的。可能pytorch-bert这个库优先判断了bert-base-chinese是一个下载路径。

**Comment by ParkHM17** [comment]
> 你把文件夹命名也改了，不要用bert-base-chinese，改成bert_base之类的。可能pytorch-bert这个库优先判断了bert-base-chinese是一个下载路径。

谢谢，我改了文件夹名字，已经解决了这个问题，太谢谢了！
