### ISSUE TITLE
测试集预测结果出错？

### ISSUE THREAD

**Issue by HJW3536** [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch#13]
貌似测试数据也是按句长切分?长句之间添加了空行来区分输入长度吗？为什么预测出来的结果空行前一个字符都掉了？导致test文件共52316行，而测试结果为50971行。。

**Comment by hertz-pj** [comment]
检查下你的测试集是否包含了一些\xoa类似的符号，不可见。
