### ISSUE TITLE
跪求数据集

### ISSUE THREAD

**Issue by xiotangyuan** [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch#14]
非常想知道您是用CLUE上的哪个数据集呀。或者是可否发到邮箱一份呢m13332392833@163.com
本人小小白，在CLUE上扒拉了半天也没找到合适的数据集，就一直跑不通
非常感谢~

**Comment by young-yhx** [comment]
请问你得到数据集了吗?得到的话可以给我的邮箱发一份吗862069753@qq.com
谢谢!!!
