### ISSUE TITLE
为啥我复现不到80.45 是我的tricks有问题吗 

### ISSUE THREAD

**Issue by SomeoneNotLikeYou** [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch#15]

**Comment by hertz-pj** [comment]
80.45指的是？

**Comment by SomeoneNotLikeYou** [comment]
我看官方给出的bert+crf ，已经到了 80多。但是我最高只有79.5，是不是有什么tricks我没有做到。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 上午10:15
收件人: ***@***.***&gt;; 
抄送: "@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch] 为啥我复现不到80.45 是我的tricks有问题吗  (#15)





 
80.45指的是？

**Comment by hertz-pj** [comment]
> 我看官方给出的bert+crf ，已经到了 80多。但是我最高只有79.5，是不是有什么tricks我没有做到。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月21日(星期三) 上午10:15 收件人: ***@***.***&gt;; 抄送: "@***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch] 为啥我复现不到80.45 是我的tricks有问题吗 (#15) 80.45指的是？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我记得官方代码也有pytorch版本的，可以对照下看看是哪块的问题。
