### ISSUE TITLE
你好，我用您的项目直接跑的话结果没有问题，但是另外开一个文件，单独加载模型进行test预测，结果很差，不知道您遇到过这个问题没有，保存和加载的代码没有改~

### ISSUE THREAD

**Issue by ZhangYi1212** [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch#17]

**Comment by hertz-pj** [comment]
应该是label2id变了？导致识别出来的结果类别都不对了。你看下识别出来的结果是不是这个问题。

**Comment by ZhangYi1212** [comment]
明白您的意思了，我试一试，非常感谢~



在 2021-06-03 16:45:22，"peiji" ***@***.***> 写道：

应该是label2id变了？导致识别出来的结果类别都不对了。你看下识别出来的结果是不是这个问题。

**Comment by hertz-pj** [comment]
#10 可以看一下这个。

**Comment by ZhangYi1212** [comment]
非常感谢！确实是这个问题，已经解决了，是我没有考虑到这个问题，您的代码里是有注意这个点的，很赞~非常感谢呀！！！
