### ISSUE TITLE
如何对测试集做预测

### ISSUE THREAD

**Issue by Coder-XIAOKAI** [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch#18]
通过您的数据集处理代码处理后的测试集标签全为‘O’，加载模型预测结束后只返回预测数量，不显示准确率等指标

**Comment by hertz-pj** [comment]
> 通过您的数据集处理代码处理后的测试集标签全为‘O’，加载模型预测结束后只返回预测数量，不显示准确率等指标

我印象中测试集就是没给标注结果的。
