### ISSUE TITLE
AttributeError: 'DataParallel' object has no attribute 'predict'

### ISSUE THREAD

**Issue by BlueSkyBubble** [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch#3]
单GPU训练会报错
RuntimeError: CUDA out of memory.

然后使用多GPU训练，然而在执行ner.py的第67行的时候会报
AttributeError: 'DataParallel' object has no attribute 'predict'

本人小白，能否帮忙指点迷津，非常感谢！！！

**Comment by hertz-pj** [comment]
没设置多gpu并行，你可能需要自己修改这部分代码。如果用单GPU，把batch size调小训练，我batch size设置的比较大。

**Comment by 550952213** [comment]
修改ner文件为def evaluate(args, data, model, id2label, all_ori_tokens):
    if isinstance(model, torch.nn.DataParallel):
        model = model.module
    model.eval()
