### ISSUE TITLE
你好，问下使用下载好的预训练模型

### ISSUE THREAD

**Issue by zchaizju** [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch#6]
我下载了一个bert-base-chinese的模型，包含config.json，pytorch_model.bin，和vocab.txt。这三个文件放到bert-base-chinese文件夹里，但是执行代码显示未能初始化模型权重，仍然要重新下载，速度很慢。请问下载好的预训练模型要如何使用呢？

**Comment by ShengJiabao** [comment]
我的是说无法loading weights file，少个.bin文件（就是pytorch_model.bin）。但是它的路径是从pytorch-transformers里的utils里加载的，就很迷。我就算把.bin文件放在bert-base-chinese下，它也不从那里加载。

**Comment by hertz-pj** [comment]
BERT_BASE_DIR=bert-base-chinese这一行改成自己下载好的路径。

**Comment by ShengJiabao** [comment]
> BERT_BASE_DIR=bert-base-chinese这一行改成自己下载好的路径。
其实...路径我是改了的，包括其他参数的路径也改好的。

**Comment by ShengJiabao** [comment]
好的谢谢你～我会再试一下的🙏


 原始邮件 
发件人: peiji<notifications@github.com>
收件人: PeijiYang/BERT-BiLSTM-CRF-NER-pytorch<BERT-BiLSTM-CRF-NER-pytorch@noreply.github.com>
抄送: Jiabao<s1505302434@163.com>; Comment<comment@noreply.github.com>
发送时间: 2020年9月26日(周六) 16:38
主题: Re: [PeijiYang/BERT-BiLSTM-CRF-NER-pytorch] 你好，问下使用下载好的预训练模型 (#6)


BERT_BASE_DIR=bert-base-chinese这一行改成自己下载好的路径。

**Comment by zchaizju** [comment]
我想问下测试的时候测试文件里有很多空格字符、对应标签为O，但是又不能把空格直接split掉，这样最后的文件长度就变掉了。请问如何调整代码来按其他字符split句子呢
